import dictionary from '../src/constants/dictionary';

export default () => ({
  media: {
    pendingFiles: [],
    hasFileUploadErrors: false,
    downloadedFiles: [],
    downloadError: null,
    loading: false,
    loaded: false,
  },
  activities: {
    error: false,
    loading: false,
    attachments: [],
    attachmentsLoading: false,
    attachmentsError: false,
    history: [
      {
        id: 'DEF456',
        baseType: 'Activity',
        type: 'Email',
        createdAt: '2018-09-17T10:34:22+00:00',
        modifiedAt: '2018-09-17T10:34:23+00:00',
        createdBy: {
          id: '9e0dca1e-0538-e811-80c9-005056825b41',
          displayName: 'DynamicsAATest Test',
          type: 'employee',
        },
        summary: 'Arrears Interaction',
        description: 'test',
        link: {
          service: 'interactions/web',
          path: '/api/v1/interactions/506669c7-80c9-4b4f-9b5b-c9f19502f23f',
        },
      },
      {
        id: 'UE21sa',
        baseType: 'Activity',
        type: 'Email',
        createdAt: '2018-09-17T10:34:22+00:00',
        modifiedAt: '2018-09-17T10:34:23+00:00',
        createdBy: {
          id: '9e0dca1e-0538-e811-80c9-005056825b41',
          displayName: 'DynamicsAATest Test',
          type: 'employee',
        },
        summary: 'Arrears Interaction',
        description: 'new test',
        link: {
          service: 'interactions/web',
          path: '/api/v1/interactions/506669c7-80c9-4b4f-9b5b-c9f19502f23f',
        },
      },
    ],
    detail: {
      type: 'Referral',
      id: 'string',
      teamName: {
        referrableTeams: [
          {
            id: 'string',
            name: 'string',
          },
          {
            id: 'string',
            name: 'string',
          },
          {
            id: 'string',
            name: 'string',
          },
        ],
      },
      detail: 'string',
      raisedBy: {
        id: 'string',
        name: 'string',
        type: 'Employee',
      },
      createdOn: '2018-09-28T13:28:15.133Z',
    },
  },
  notes: {
    items: [
      {
        id: 'a143b7a5-0f6e-4eeb-9398-a897c3d2cec7',
        caseId: '00000000-0000-0000-0000-000000000000',
        created: { by: null, on: '2018-10-31T14:41:31+00:00' },
        modified: { by: null, on: '2018-10-31T14:41:31+00:00' },
        subject: 'Note added via Arrears',
        text:
          'this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note this is a very long note ',
      },
    ],
    loading: false,
    loaded: true,
    error: false,
  },
  arrears: {
    filterLabel: 'aFilter',
    items: [
      {
        businessUnit: 'PRH',
        id: 'foo',
        bar: 'baz',
        legalReferralCase: {
          formName: 'Friendly Form Name | legalReferralCaseFormName',
          lastSubmissionId: 'DEF456',
        },
        nospServeError: false,
        tenancyId: 'ABC123',
      },
    ],
    loadingArrears: false,
    loadingArrearsStats: false,
    nospServeError: false,
    nospLoading: false,
    resultsCount: 1,
    stats: {},
  },
  sendCorrespondence: {
    loading: false,
    error: false,
    submitted: false,
    correspondenceDocuments: [],
    generatePreviewError: false,
    generatePreviewLoading: false,
    loadingTemplates: false,
    templatesError: false,
    loadingSubstitutions: false,
    mandatoryAttachments: [],
    printerOptions: [],
    recipient: '',
    sendingMethod: '',
    substitutionFields: [],
    template: {
      id: '',
    },
    templates: [
      {
        id: '346c840d-ffbf-e811-80cf-005056825b41',
        name: 'Template for Customer 1',
        potentialSendingMethods: ['System'],
        templatePreviewImageLink: 'img',
      },
      {
        id: '35131c95-ffbf-e811-80cf-005056825b41',
        name: 'Template for Customer 2 - Folio',
        potentialSendingMethods: ['System'],
        templatePreviewImageLink: null,
      },
    ],
    templatePreviewImage: '',
  },
  tasks: {
    loading: false,
    statuses: {
      Arrears: {
        Open: {
          count: 10,
        },
      },
    },
    items: [
      {
        id: 'foo',
        type: 'manual',
        status: 'Open',
        title: 'this is a title',
        dueDate: '2018-08-27T15:08:44+00:00',
        owner: {
          id: '9e0dca1e-0538-e811-80c9-005056825b41',
          name: 'DynamicsAATest Test',
          type: 'systemusers',
        },
        regardingObjectModel: { id: 'bar', type: 'Arrears' },
      },
    ],
    summaryItems: [
      {
        id: 'foo',
        type: 'manual',
        status: 'Open',
        title: 'this is a title',
        dueDate: '2018-08-27T15:08:44+00:00',
        owner: {
          id: '9e0dca1e-0538-e811-80c9-005056825b41',
          name: 'DynamicsAATest Test',
          type: 'systemusers',
        },
        regardingObjectModel: { id: 'bar', type: 'Arrears' },
      },
    ],
  },
  customer: {
    profile: {
      loading: false,
      address: {
        line1: '82 Prince Consort Road',
        line2: null,
        city: 'KELBROOK',
        postcode: 'BB8 2SN',
      },
      dateOfBirth: '1995-02-01T00:00:00',
      emailAddress: 'tworkwise@nhhg.org.uk',
      firstName: 'MARK',
      fullName: 'MARK BROWNIE',
      homeTelephoneNumber: null,
      id: '71f86a99-03f6-e711-80c5-005056825b41',
      lastName: 'BROWNIE',
      mobileTelephoneNumber: '07736171831',
      partyIdentifier: '12345',
      paymentReferenceNumber: '00012345',
      productHolding: {
        id: '00000000-0000-0000-0000-000000000000',
        asset: {
          id: '00000000-0000-0000-0000-000000000000',
          address: {
            line1: null,
            line2: null,
            city: null,
            postcode: null,
          },
          block: {
            name: null,
            propertyReferenceNumber: null,
          },
          borough: null,
          description: null,
          estate: {
            name: null,
            propertyReferenceNumber: null,
          },
          gasCertificate: false,
          insurance: false,
          legalEntity: null,
          offerType: 'NHHO Leasehold',
          name: null,
          numberOfBedrooms: 0,
          bedspace: 0,
          floor: null,
          patch: {
            housingOfficer: {
              domainName: null,
              emailAddress: null,
              fullname: null,
              homeTelephoneNumber: null,
              id: '00000000-0000-0000-0000-000000000000',
              mobileTelephoneNumber: null,
              patchName: null,
              team: null,
              title: null,
              username: null,
            },
            name: null,
          },
          propertyReferenceNumber: null,
          propertySubType: null,
          shortDescription: null,
          t1Code: null,
          t2Code: null,
          type: null,
          scheme: null,
        },
        endDate: null,
        name: null,
        startDate: '2017-12-01T00:00:00+00:00',
        tenancyTypeName: 'LEASE',
        tenureType: 'MONTHLY SERVICE CHARGE ONLY',
        termLength: null,
        tenancyReferenceNumber: '1112345',
      },
      type: null,
      visitRules: null,
      securityRules: null,
      contactRules: null,
    },
    accounts: [
      {
        currentBalance: -2442.36,
        typeCode: 'REN',
        typeName: 'RENT ACCOUNT',
        paymentReference: '1234567',
      },
      {
        currentBalance: 53.4,
        typeCode: 'SUN',
        typeName: 'SUNDRY ACCOUNT',
        paymentReference: '7654321',
      },
    ],
  },
  dictionary: { ...dictionary() },
  forms: {
    error: false,
    loading: false,
    legalReferralCaseFormName: {
      id: 'd96d6e3e-b377-472a-9f91-415c07bf68a2',
      submissions: ['732e2ea4-ee21-488b-b863-2f17dfa9539d'],
    },
    formSubmitted: false,
  },
  housingofficersearch: {
    loading: false,
    error: false,
    searchResults: [
      {
        domainName: 'NHILL\\aoflaherty',
        emailAddress: 'Aisling.OFlaherty@nhhg.org.uk',
        fullname: "Aisling O'Flaherty",
        homeTelephoneNumber: '02038150210',
        id: '01973660-bd18-e811-80c8-005056825b41',
        mobileTelephoneNumber: null,
        patchName: 'CA814',
        team: {
          id: '17104610-f317-e811-80c8-005056825b41',
          name: 'PRH',
        },
        title: 'Housing Officer',
        username: 'aoflaherty',
      },
      {
        domainName: 'NHILL\\afraserbailey',
        emailAddress: 'Akima.F.Bailey@nhhg.org.uk',
        fullname: 'Akima Fraser Bailey',
        homeTelephoneNumber: '02038150530',
        id: '03973660-bd18-e811-80c8-005056825b41',
        mobileTelephoneNumber: null,
        patchName: null,
        team: {
          id: '17104610-f317-e811-80c8-005056825b41',
          name: 'PRH',
        },
        title: 'Housing Operations Manager',
        username: 'afraserbailey',
      },
      {
        domainName: 'NHILL\\apettifor',
        emailAddress: 'Ayesha.Pettifor@nhhg.org.uk',
        fullname: 'Ayesha Pettifor',
        homeTelephoneNumber: '02038150804',
        id: '37973660-bd18-e811-80c8-005056825b41',
        mobileTelephoneNumber: null,
        patchName: null,
        team: {
          id: '38104610-f317-e811-80c8-005056825b41',
          name: 'Business Improvement Directorate',
        },
        title: 'Team Co-ordinator',
        username: 'apettifor',
      },
    ],
  },
  navigation: {
    entryPoint: '/',
  },
  notifications: {
    items: [
      {
        description: 'some notification',
        title: 'notification title',
        notificationType: 'confirmation',
      },
    ],
  },
  referral: {
    error: false,
    loading: false,
    referralTeams: [
      {
        id: 'rt-1',
        name: 'Benefits advice',
      },
      {
        id: 'rt-2',
        name: 'Tenancy support',
      },
    ],
  },
  ribbon: {
    title: 'Dashboard',
    breadcrumb: [
      {
        label: 'Dashboard',
        path: '/',
      },
    ],
    dashboardUrl: '/',
    showDashboardIcon: true,
    dashboardButtonText: 'Dashboard',
  },
  user: {
    initialised: true,
    waiting: false,
    loggedIn: true,
    profile: {
      createdAt: '2018-01-17T10:31:48.209Z',
      emailAddress: 'mbrownie@test.com',
      id: 'auth0|5a5f2614de16214961915a31',
      lastLoginAt: '2018-03-26T11:04:23.262Z',
      name: 'Mark Brownie',
      fullname: 'Mark Brownie',
      patchName: 'ABC123',
      pictureUrl:
        'https://s.gravatar.com/avatar/b4711b09c3f253d6999f146c91c7d057?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fmb.png',
      updatedAt: '2018-03-26T11:04:23.262Z',
      userIdentities: {
        hasAtLeastOneEmailIdentity: true,
        hasOnlyEmailIdentities: true,
        identities: [
          {
            connection: 'Username-Password-Authentication',
            isSocial: false,
            provider: 'auth0',
            userId: '5a5f2614de16214961915a31',
          },
        ],
      },
      userProfile: {
        assetPartyId: '12345',
        crmContactId: '71f86a99-03f6-e711-80c5-005056825b41',
        dateOfBirth: '1995-02-01T00:00:00Z',
        firstName: 'Mark',
        gender: null,
        lastName: 'Brownie',
      },
    },
    idTokenPayload: {},
    userType: '',
    userEmail: '',
    id: {
      'http://nhhg.org.uk/claims/user_type': 'customer',
      'http://nhhg.org.uk/claims/customer_type': 'tenant',
      'http://nhhg.org.uk/claims/given_name': 'Mark',
      'http://nhhg.org.uk/claims/family_name': 'Brownie',
      'http://nhhg.org.uk/claims/email_address': 'mbrownie@test.com',
      'http://nhhg.org.uk/claims/crm_contact_id': '71f86a99-03f6-e711-80c5-005056825b41',
      iss: 'https://nhh-dev.eu.auth0.com/',
      sub: 'auth0|5a5f2614de16214961915a31',
      aud: '15jZW53Nd1Kt0ZanCD6tl89aI7sBgDJj',
      iat: 1522062263,
      exp: 1522098263,
    },
  },
  features: {
    payments: true,
  },
  pause: {
    activePause: {
      status: 'Active',
      reasonId: 'newbenefituc',
      endDate: '2018-10-18T00:00:00Z',
      furtherDetail: 'This is a pause',
      isExtended: false,
      originalStartDate: '2018-10-04T00:00:00Z',
      lastModifiedAt: '2018-10-04T15:32:35Z',
      lastModifiedBy: 'SYSTEM',
      createdAt: '2018-10-04T15:32:32Z',
      createdBy: 'Stephanie Golder',
      isManagerNotified: false,
      approvalDetail: {
        userName: 'system',
        decisionDate: '2018-10-04T00:00:00Z',
        isApproved: true,
      },
      owner: {
        id: '039a3660-bd18-e811-80c8-005056825b41',
        name: 'Stephanie Golder',
        type: 'systemuser',
      },
      raisedBy: {
        id: '039a3660-bd18-e811-80c8-005056825b41',
        name: 'Stephanie Golder',
        type: 'systemuser',
      },
      cancelReason: '',
      notifcationDetail: { notifiedUserName: 'Hannah Ike', wasNotified: false },
    },
    pauseRules: [
      {
        id: 'abc123',
        title: 'A reason',
        myRule: {
          endDate: '2019-07-27T13:56:50.951Z',
        },
        managerRule: {
          endDate: '2019-08-28T13:56:50.951Z',
        },
      },
      {
        id: 'def456',
        title: 'Another reason',
        myRule: {
          endDate: '2019-07-27T13:56:50.951Z',
        },
        managerRule: {
          endDate: '2019-08-28T13:56:50.951Z',
        },
      },
    ],
    loading: false,
  },
  patch: {
    teamMembers: [
      {
        fullname: 'Test_1 HO',
        name: 'Test_1 HO',
        patchName: 'PTCPRH01',
        src: 'https://url.to/profile/image.jpg',
      },
    ],
    patchList: [
      {
        fullname: 'Test_1 HO',
        name: 'Test_1 HO',
        patchName: 'PTCPRH01',
        src: 'https://url.to/profile/image.jpg',
      },
    ],
  },
  paymentPlan: {
    error: false,
    loading: false,
    plan: {
      id: 'id',
      type: 'Personal',
      status: 'string',
      installment: {
        amount: 40,
        period: 1,
        schedule: 'Weekly',
      },
      endDate: '2018-12-23T13:30:24.051Z',
      startDate: '2018-07-23T13:30:24.051Z',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo.',
      raisedBy: {
        id: '13123',
        name: 'Mabelle Ortega',
        type: 'Employee',
      },
      owner: {
        id: '31313',
        name: 'Rosa Malone',
        type: 'Employee',
      },
      hasAttachments: true,
    },
  },
  tenancy: {
    addressLine1: '246B WESTBOURNE PARK ROAD',
    addressLine2: null,
    addressLine3: null,
    addressCity: 'LONDON',
    addressPostcode: 'W11 1EL',
    tenants: [
      {
        emailAddress: 'joe.bloggs@test.com',
        firstName: 'Joe',
        contactId: 'ABC123',
        lastName: 'Bloggs',
        mobileTelephoneNumber: '0123456789',
        partyIdentifier: '31928',
      },
      {
        emailAddress: 'jane.doe@test.com',
        firstName: 'Jane',
        contactId: 'DEF456',
        lastName: 'Doe',
        mobileTelephoneNumber: '0987654321',
        partyIdentifier: '41527',
        isVulnerable: true,
      },
    ],
  },
  interactions: {
    activity: {},
    error: false,
    loading: false,
    activityTypes: [],
    thirdParties: undefined,
    thirdPartiesError: false,
  },
});
