import PropTypes from 'prop-types';

export const labelsPropTypes = PropTypes.shape({
  address: PropTypes.string.isRequired,
  addressCity: PropTypes.string.isRequired,
  addressLine1: PropTypes.string.isRequired,
  addressLine2: PropTypes.string.isRequired,
  addressLine3: PropTypes.string.isRequired,
  addressPostcode: PropTypes.string.isRequired,
  backButton: PropTypes.string.isRequired,
  closeTemplate: PropTypes.string.isRequired,
  decline: PropTypes.string.isRequired,
  emailAddress: PropTypes.string.isRequired,
  generatedCorrespondence: PropTypes.string.isRequired,
  generateDraft: PropTypes.string.isRequired,
  letterPrintingMethods: PropTypes.string.isRequired,
  mobilePhone: PropTypes.string.isRequired,
  nextButton: PropTypes.string.isRequired,
  previewTemplate: PropTypes.string.isRequired,
  recipient: PropTypes.string.isRequired,
  sendingMethod: PropTypes.string.isRequired,
  submitButton: PropTypes.string.isRequired,
  template: PropTypes.string.isRequired,
  viewPreview: PropTypes.string.isRequired,
  viewPreviewsBeforeProceeding: PropTypes.string.isRequired,
  viewTemplate: PropTypes.string.isRequired,
});

export const errorTextLabels = PropTypes.shape({
  addressCity: PropTypes.string.isRequired,
  addressLine1: PropTypes.string.isRequired,
  addressLine2: PropTypes.string.isRequired,
  addressLine3: PropTypes.string.isRequired,
  addressPostcode: PropTypes.string.isRequired,
  emailInvalid: PropTypes.string.isRequired,
  emailMissing: PropTypes.string.isRequired,
  mergeFieldMissingData: PropTypes.string.isRequired,
  mergeFieldMissingDataInvalidData: PropTypes.string.isRequired,
  mobileInvalid: PropTypes.string.isRequired,
  mobileMissing: PropTypes.string.isRequired,
  noTemplateFound: PropTypes.string.isRequired,
  printMethodMissing: PropTypes.string.isRequired,
  recipient: PropTypes.string.isRequired,
  sendingMethod: PropTypes.string.isRequired,
  template: PropTypes.string.isRequired,
});
